### ISSUE TITLE
General feedback (copied from Brisbane Slack)

### ISSUE THREAD

**Issue by parameme** [davekinkead/school-performance#1]
Hi Dave,

Great paper,  very interesting... just some cosmetic issues in my first read.

misspell 

> Events in the simulation will occur during a generic time **perior** called a tick.

grammar

> This could be **modelling** in a variety of ways but for simplicity we will just apply a linear factor with the result constrained between 0.0 and 1.0.
> In every tick cycle, we **run call** simulation's teach and graduate methods.

ui
Is it possible to include a [stream line-graph?] historical log of values to graphically record and relate the simulations relative school weighting in a more tangible, quantitative sense?

Kind Regards,
Lachlan Pitts (@parameme)

**Comment by davekinkead** [comment]
Thanks for the feedback @parameme.  Not concerned with spelling/grammar just yet as it needs to be heavily rewritten but can you explain a little about what you think a stream line graph would do? Which values in particular?

Do you mean the range of skew-impact-selectivity values where this occurs and where it does not?

**Comment by parameme** [comment]
Explained via Brisbane Slack

A two line (one per school) historical line graph recording the average student ability for each school over time.
